### ISSUE TITLE
Does Redis 4 no longer have the return_buffers property?

### ISSUE THREAD

**Issue by tavareshenrique** [redis/node-redis#1775]
When I migrated to Redis 4 I missed the `return_buffers` property, I didn't find anything in the documentation talking about it.

Has it been discontinued?

![image](https://user-images.githubusercontent.com/27022914/145415848-a2de47bc-0eb0-4211-8335-14d6a705d712.png)

**Comment by leibale** [comment]
In order to sent buffers to Redis, just pass `Buffer`s as arguments:
```javascript
await client.get(Buffer.from('key'));
await client.set('key', Buffer.from('value'));
```

In order to use the `GET` command and get the reply as `Buffer` - use `.getBuffer`:
```javascript
await client.getBuffer('key'); // `null | Buffer`
```

with `.sendCommand`:
```javascript
await client.sendCommand(['GET', 'key'], null, true);
```

Which command do you want to use?

**Comment by tavareshenrique** [comment]
Hey @leibale, thanks for your answer!

I used in the command that creates the connection, the `createClient`, I was doing this in version `3.1.2`. but I realized that in version 4 of redis the `return_buffers` no longer exists.

So, it is no longer possible to use in `createClient`?

**Example:**
![redis](https://user-images.githubusercontent.com/27022914/145455082-f7cc1fc1-c831-4363-ad8f-58fef65eb2a5.png)

**Comment by leibale** [comment]
The `return_buffers` option on the client does not exist anymore, but you can still use `Buffer`s as I've shown in my last comment

**Comment by tavareshenrique** [comment]
Thank you so much @leibale

**Comment by jleppert** [comment]
This API is worse, because now you have to go through and update the invocation everywhere instead of just passing a flag in the constructor. There's a big range of apps that want to only deal with buffers, not to mention the silent breaking of compatibility with no warnings.

Also, it's inconsistent, for example in client.lRange(Buffer.from('....'), when passing a key as a buffer it doesn't work as expected and returns a string instead in the list that is returned.

At least when moving to a worse API for no apparent reason or benefit, document it, and make your decision internally consistent! Otherwise all you're doing is wasting people's time.

**Comment by BCsabaEngine** [comment]
I spent soha time to resolve it. My solution is: use buffer.toString("binary") when you SET, and use Buffer.from(str, "binary) when you GET. Data size will the same and buffer works.
ps: I use msgpackr for convert obj to buffer.

**Comment by BCsabaEngine** [comment]
Redis lib handles binary, but thinks buffer contains string data. The BINARY need when there is any nonchar thing in binary, like jpeg content or executable binary. But the best is to use it every time.

You should use it consequently: when you use at set, use it at get.

```
id=elementary type, value=buffer
void client.set(id, Buffer.toString(value, 'binary'));
const value = Buffer.from(client.get(id), 'binary');
```

```
id=buffer, value=buffer
void client.set(Buffer.toString(id, 'binary'), Buffer.toString(value, 'binary'));
const value = Buffer.from(client.get(Buffer.toString(id, 'binary')), 'binary');
```
