### ISSUE TITLE
How to not wait  connection for  get command

### ISSUE THREAD

**Issue by mogadanez** [redis/node-redis#1888]
I'm using Redis as an optional cache layer.
if its failed to connect   - it is wait infinitely on GET command and not 

tried to set `commandsQueueMaxLength:0`

is it any other way to change behavior  to fail on operations if its not yet connected?
 or in worse case  specify operation timeout

**Environment:**
 - **Node.js Version**: 14
 - **Redis Server Version**: 6.0.5
 - **Node Redis Version**: 4.0.3
 - **Platform**:  Mac OS 12

**Comment by NathanielWroblewski** [comment]
Experiencing the same issue where `client.get` hangs infinitely

**Comment by leibale** [comment]
@mogadanez @NathanielWroblewski dose the new [`disableOfflineQueue`](https://github.com/redis/node-redis/blob/master/docs/client-configuration.md) feature solves this issue? (it's not in npm yet)

**Comment by onezone-pete** [comment]
I have the same problem, when redis server is in a broken state, the redis client just hangs up and never returns an error

**Comment by mnoorenberghe** [comment]
> dose the new [`disableOfflineQueue`](https://github.com/redis/node-redis/blob/master/docs/client-configuration.md) feature solves this issue?

It helps but it's still not straightforward to configure this client as an optional cache layer. Ideally the client would reconnect in parallel to returning failures on `get`/`set` but currently it seems like `get`/`set` still block on some of the `reconnectStrategy`'s attempts so the redis client can actually add latency to a request rather than speeding up data accesses (depending on the number used for the reconnect timeout).

**Comment by leibale** [comment]
@mnoorenberghe sorry for the huge delay... when `disableOfflineQueue` is `true`, when the socket disconnects all the commands in the queue will be rejected **immediately**.
