### ISSUE TITLE
Using `hGetAll` with binary keys

### ISSUE THREAD

**Issue by miroslavLalev** [redis/node-redis#2037]
Hey all,

I've stumbled across a weird behavior when trying to fetch all data from a hash that contains binary keys - even when passing `returnBuffers`, the keys in the returned object are strings. Here's a minimal reproducible example:
```
const client = redis.createClient();
await client.connect();

const key = Buffer.from('b40711a88c7039756fb8a73827eabe2c0fe5a0346ca7e0a104adc0fc764f528d', 'hex');
await client.HSET({ returnBuffers: true },"testhash", key, 1);

// The `res` value is an object with a string key, instead of a map with buffer key.
const res = await client.hGetAll({ returnBuffers: true },"testhash");

await client.del("testhash");
```

I've also checked the code and it seems that this is enforced by the reply transformer here:
```
export function transformTuplesReply(
    reply: Array<RedisCommandArgument>
): Record<string, RedisCommandArgument> { // <-- record here is defined with key 'string', instead of 'string | Buffer'
    const message = Object.create(null);
    for (let i = 0; i < reply.length; i += 2) {
        message[reply[i].toString()] = reply[i + 1]; // <-- key here is converted to string
    }
    return message;
}
```

Is this expected? I have not tested all hash functions, but I can see that most others seem to work properly with binary keys.

**Comment by leibale** [comment]
"Please note that all keys in the square bracket notation are converted to string unless they're Symbols, since JavaScript object property names (keys) can only be strings or Symbols (at some point, private names will also be added as the [class fields proposal](https://github.com/tc39/proposal-class-fields) progresses, but you won't use them with [] form)."

(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects#objects_and_properties)

```javascript
const assert = require('assert/strict');

assert.deepEqual(
    {
        [Buffer.from('buffer')]: 'value'
    },
    {
        buffer: 'value'
    }
);
```
