### ISSUE TITLE
4.1.0 hGetAll returns an empty object instead of null if the key doesn't exist

### ISSUE THREAD

**Issue by snowbldr** [redis/node-redis#2161]
When calling hGetAll with a key that does not exist, in version 3.x, it would return a falsey value (null).
In 4.1.0, it returns an empty object, which is truthy.

here's a failing test to illustrate the issue.

this passes with 3.x version of the client.

```javascript
it('should return falsey for non-existing keys', async()=>{
    const res = await client.hGetAll('non-existent-key')
    expect(res).toBeFalsy()
})
```

For now I've just had to add an additional exists command before every key lookup, which is not ideal.

It seems the transformTuplesReply should return null if the reply is empty.

**Comment by MatanYemini** [comment]
I agree that it is less comfortable and a "breaking change" from v3.

I would recommend adding "hGetAllWrapper" to your code that will wrap it and return null in case of an empty object

But take into account that it is not a mistake. Since on redis-cli if you will try to do `hgetall {random-non-existing-key}` you will get an empty array, so this variant is closer to the origin.

I would recommend closing this discussion.

**Comment by snowbldr** [comment]
The only real downside I see with that approach is that it adds the overhead of having to do Object.keys(result).length, which involves iterating and counting all of the keys returned. 

There's no avoiding that without knowledge of the length of the original response. 

Perhaps this could be modified to return an es6 Map instead of an object? That would allow using the size property and would avoid needing to count the properties again.

**Comment by MatanYemini** [comment]
@snowbldr I would less recommend it since it will get us diverged from the original Redis commands.

I usually recommend to developers to name their abstractions as close to the original API naming, since then it is easier to prevent code duplication and find functions. (so I am following my role here).

(this is besides the obvious es6 requirement you are adding)

**Comment by leibale** [comment]
As @MatanYemini pointed out, from the point of view of Redis, an empty hash and null are equivalent:

```
> TYPE key
none
> HSET key field value
OK
> TYPE key
hash
> HDEL key field
1
> TYPE key
none
```

But, as @snowbldr pointed out, there is no "straightforward" way to check if an object is empty

@guyroyse @simonprickett WDUT?

**Comment by simonprickett** [comment]
@leibale I'm OK with the current behaviour - yes it's a breaking change from v3, but v4 contains many such breaking changes.

**Comment by guyroyse** [comment]
@leibale I the same thing with Redis OM for Node.js that Node Redis 4.x is doing. Redis can't distinguish between an object full of nulls and an object that _is_ null. Gotta pick one of them.

**Comment by leibale** [comment]
In RESP3 Redis replies with `%0` (empty hash) and not `_` (null)
