### ISSUE TITLE
Is await important even if you don't need the result of an operation?

### ISSUE THREAD

**Issue by v-flashpoint** [redis/node-redis#2249]
Hi all,

I have what's probably a really basic question, but I thought I ought to ask just in case I'm doing something daft.

If I'm doing something really basic, like a SET, do I still need to use await? At the moment, I'm using await for everything, but for those operations where I don't actually need the result, should I drop the await? Am I gaining anything by using it (would Node wait for the result of the SET operation synchronously otherwise?), or am I just making things slower by awaiting things I don't need?

Quick illustration of the sort of thing I'm talking about:
```
async function setstuff(){
	redis.set('1234','true');

	var score = await redis.zIncrBy('counter', 5, 'mycounter');

	if(score > 100){
		//do something
	}

}
```

**Comment by leibale** [comment]
By `await`ing a command promise, you are making sure that the command was actually executed on the server (even if the reply content does not matter too much), so if you wanna make sure the command was executed successfully on the server -  `await` it. In case the command is "nice to have", (for example, you are using Redis as a cache server) - don't `await` the promise, just make sure to add a `.catch` handler, in case it'll reject for some reaon (otherwise your process will crash with "Unhandled promise rejection" error)

**Comment by v-flashpoint** [comment]
Thanks! It's pretty much as I was thinking then. Is there a way to catch when commands aren't executed? Under really high loads, I've noticed some commands seem to not be being executed on Redis - is the only way to check for this to see if the result your awaiting comes back blank? I guess eventually the promise must time out?

**Comment by leibale** [comment]
```javascript
// async await version
try {
  await client.set('key', 'value');
} catch (err) {
 // ...
}

// .catch callback version
client.set('key', 'value').catch(err => {
  // ...
});

**Comment by leibale** [comment]
You can change the timeouts, and maybe `disableOfflineQueue`
