### ISSUE TITLE
`XREAD BLOCK $` never resolves

### ISSUE THREAD

**Issue by hesxenon** [redis/node-redis#2258]
In redis-cli I can do

`XREAD BLOCK 0 STREAMS test $`

then open another client and do 

`XADD test * foo bar`

and the `XREAD` in the first client completes.

It is my understanding that with isolated execution I should be able to achieve the same result, something like

```typescript
const client = createClient({ url: "redis://localhost:6379" });
await client.connect();
client
  .XREAD(
    commandOptions({ isolated: true }),
    { key: "test", id: "$" },
    { BLOCK: 0 },
  )
  .then(console.log);

client.XADD("test", "*", { foo: "bar" });

```

should log replies to the console, no?

I'd prefer this _a lot_ over the endless loop given in the examples folder

**Environment:**
 - 18.8.0
 - 7.0.4
 - 4.3.1
 - EndeavourOS Kernel 5.19.5-arch-1

**Comment by hesxenon** [comment]
this actually seems to not be related to a timeout of `0` but rather the special id `"$"`; the example runs fine if you pass in e.g. `"0"`.

**Comment by leibale** [comment]
The reason the code is not working as you would've expected it to is that there is a race condition here: you are executing two commands on two sockets, but you need to make sure that "XREAD" will be executed before "XADD", otherwise "XREAD" will wait for the next "XADD" to the stream.

I think that the only solution to that will be to add a `onWrite` callback on the command, but unfortunately that's not supported by promises...

@guyroyse @simonprickett ideas?

**Comment by hesxenon** [comment]
promises are eagerly executed, meaning that if there's a race condition it's either
- because the messages sent over the socket arrive at the redis instance out of order. 
- because the messages are not sent synchronously when the XREAD/XADD are called

I'd expect this library to ensure commands sent to the server arrive in the order they are sent.

I'm not quite sure what you mean by `onWrite` callback, but delay that can be achieved with a callback can also be wrapped into a promise.

--

The real world use case here is e2e testing in the context of event sourcing; maybe I have abused redis here and streams aren't meant to accomodate event sourcing?

**Comment by hesxenon** [comment]
apologies if the previous comment sounded too harsh, what I meant by "expect" is that any other behaviour would be surprising and while technically possible I'd think this library would also exist to tackle and alleviate such problems.

**Comment by leibale** [comment]
"because the messages sent over the socket arrive at the redis instance out of order."
with `isolated: true`, you are actually using two sockets, so they might arrive at the server out-of-order..

"because the messages are not sent synchronously when the XREAD/XADD commands are called"
Any command is being sent asynchronously.
If two commands are executed in the same socket (without `isolated`) - Redis promises they will run in order
```javascript
await Promise.all([
  client.del('key'),
  client.set('key', value);
  client.get('key')
]);

// the reply will be:
[
  1 || 0,
  'OK',
  'value'
]
```

But if two commands are executed on two different sockets, they might run at different order:
```javascript
await Promise.all([
  client.del('key'),
  client.set(commandOptions({ isolated: true }), 'key', value);
  client.get('key')
]);

// the reply will be:
[
  1 || 0,
  'OK',
  'value' || null
]
```

**Comment by hesxenon** [comment]
The commands are async, but dispatching them should be sync, right?

And while the commands might arrive out of order when using two sockets
that's exactly what I'd use a driver for - to ensure that the commands
still arrive in order. How many sockets are being used should imho not be
the concern of the user, that's the drivers job.

**Comment by leibale** [comment]
It's not something the client can do, because the server is not replying with "entering block mode" event, so the client cannot know if the command is "on the way" to the server or if it was processed by the server and the client is in blocking mode
