### ISSUE TITLE
CHANGELOG.md is missing all versions after 4.0.2

### ISSUE THREAD

**Issue by eliliam** [redis/node-redis#2301]
I'm working on upgrading Redis and was following the changelog, but noticed that the latest version in the CHANGELOG.md is 4.0.2, whereas the actual latest version is 4.3.1. Is this something that can be updated to contain the changes from versions between 4.0.2 and 4.3.1?

**Comment by leibale** [comment]
for now you can use [github releases page](https://github.com/redis/node-redis/releases) (I'll update this file next week)

**Comment by eliliam** [comment]
Thank you! The github release page is great, but my biggest issue with it is that it's super bloated, showing releases for all packages, and a significant amount of screen real estate is taken up by assets and contributers. Having just the changes in the CHANGELOG.md would make upgrading significantly easier.

**Comment by mdouglass** [comment]
I'm going to go one step further and say using the releases page isn't reasonable or even possible. I needed to review changes between redis 4.3.1 and 4.5.1 today so we could make a decision about whether it was safe to upgrade.

The release notes for 4.5.1 are:
> upgrade @redis/client

Immediately, my process of reviewing changes can't continue because I don't know:
a) which version of @redis/client redis 4.3.1 was dependent on
b) which version of @redis/client redis 4.5.1 is dependent on

**Comment by leibale** [comment]
We're planning to automate the release process, and part of the automation will be to update the `CHANGELOG.md` for each package, but we didn't get there yet.
Anyway, from now on instead of just "upgrade @redis/client" I'll make sure to include the versions (before & after) as well.

**Comment by mdouglass** [comment]
Thanks, I appreciate that.
