### ISSUE TITLE
Question: client producing an uncought exception when no listener is attached?

### ISSUE THREAD

**Issue by Loki-Afro** [redis/node-redis#2696]
Hi there,

I consider myself as a nodejs noobie, so bare with me

```
	const client = redis.createClient({
		url: redisUrl,
	});

       client.connect().catch((err) => logger.error(err));
       ....
```

this code words, its a valid url, connect works, etc
now at some point it looses connection to redis
resulting in an uncaught exception, app dies

okay, everything fine

now when adding

```
	client.on('connect', () => console.log('Redis Client Connect'));
	client.on('error', (err) => console.log('Redis Client Error', err));
```

those listeners, i think the second is the relevant one, the error is CATCHED and thus the app does not die and actually reconnects to redis if is reachable again.

Now finally my question: how does it work, how can adding a listener result in that there is no uncatched exception being thrown and instead is being catched?

**Comment by leibale** [comment]
While I agree with you that the API is not very friendly, this is how `EventEmitter` (a node.js built-in) works, and it's not specific to this package. Maybe we should've used a different name instead of "error", but that ship has sailed..

"⚠️ You MUST listen to error events. If a client doesn't have at least one error listener registered and an error occurs, that error will be thrown and the Node.js process will exit. See the [EventEmitter docs](https://nodejs.org/api/events.html#events_error_events) for more details."

https://github.com/redis/node-redis?tab=readme-ov-file#events

**Comment by Loki-Afro** [comment]
@leibale thanks for pointing me in the right direction

one small caveat though, the link in the readme is incorrect, it is supposed to be https://nodejs.org/api/events.html#error-events not https://nodejs.org/api/events.html#events_error_events i guess
