### ISSUE TITLE
Handling of `inf` and `-inf`

### ISSUE THREAD

**Issue by Prinzhorn** [redis/node-redis#576]
Given this example

```
redis 127.0.0.1:6379> ZADD websites +inf www.google.com
(integer) 1
redis 127.0.0.1:6379> ZADD websites 20 www.github.com
(integer) 1
redis 127.0.0.1:6379> ZRANGE websites 0 -1 WITHSCORES
1) "www.github.com"
2) "20"
3) "www.google.com"
4) "inf"
```

I was expecting the score for Google to get converted to `+Infinity` when using the value in JS, but I just get the string `"inf"`.

Is this something that has been done on purpose? Because in the other direction it works as expected (passing `+Infinity` on the JS side results in `inf` in redis)

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
This will take a while as it'll be a bc change but I'd like to rewrite zrange to return as a object. In that case I'd also rewrite the inf to a JS Infinity
