### ISSUE TITLE
Horrible eval implementation

### ISSUE THREAD

**Issue by sebastian-nowak** [redis/node-redis#722]
I have no idea what was the reasoning behind overwriting generated eval function with another one, which has a terrible performance. Current implementation calculates sha1 of source code every time which is slow under heavy load, tries evalsha, waits for a reply and then sends actual eval to execute raw script. Seriously, guys? It should be written correctly or not written at all.

A correct, fast implementation allows user to load his scripts, cache sha1 in a [scriptName -> sha1] map and then eval them by name. And if someone wants to execute raw script without caching it on server side, let us do it and don't ruin the performance with useless calculations and round trips. It's not documented anywhere and I'd have missed it if I wasn't checking the source while looking for something else.

I'm not asking for a better script support, just please, don't make it worse.

**Comment by rootslab** [comment]
I think a PR from you could be a solution ;)
You can give a look to my implementation for caching scripts in __[spade](https://github.com/rootslab/spade#lua-cache-and-script-methods)__

**Comment by BridgeAR** [comment]
@sebastian-nowak are you up for a PR?

**Comment by BridgeAR** [comment]
@sebastian-nowak I'll remove the eval implementation as it is right now but it would be nice if you would implement a new way to handle this properly.

**Comment by simontabor** [comment]
there are modules that handle efficient `eval` / `evalsha` abstraction -  https://github.com/thedeveloper/scripty being one that we've built.

**Comment by BridgeAR** [comment]
Yeah... I'm thinking about if #371 would actually not have been a good idea... especially, since the work seems to be very promising @simontabor what do you think? When I stated that it should not go into core I first wanted to make sure that all the current features are actually working properly without adding other things. But I guess we are on a good way and the code is way cleaner now and it is already way easier to maintain it.

@paixaop would you actually mind to reopen the PR and get that done? That should be a very good alternative to the way it was :)

**Comment by simontabor** [comment]
#371 has *very* similar code/usage to what I've just updated scripty to do... it's now 0 dependency and if you check out the README you'll see usage examples...

https://github.com/simontabor/scripty/tree/run

I don't think I agree with adding the script name as a prototype command like #371 does, but otherwise it's pretty much exactly the same but with a few extra failsafes

**Comment by Janpot** [comment]
ported my `then-redis-scripts` back to using `node_redis`. Another variation on the theme:

**Comment by BridgeAR** [comment]
Reference: #178

**Comment by dkrieger** [comment]
What is the status here? Is there a recommended helper lib to manage this functionality? Neither of the two linked in here have even 10 stars on github.
