### ISSUE TITLE
Command timeout

### ISSUE THREAD

**Issue by gootik** [redis/node-redis#941]
We recently ran into a problem where our redis cluster was taking a very long time to respond (for reasons that don't really matter). It would be nice to define a `max_command_timeout` in the settings so that a command is killed with an error sooner, than waiting forever for a system/network layer timeout.

**Comment by BridgeAR** [comment]
Hm, I was quite sure there would be a feature request for this but I can't find it right now.

**Comment by BridgeAR** [comment]
I had a look into this and it is really difficult to do this from the client side. If the command takes to long you might want to use [slowlog](http://redis.io/commands/slowlog) to identify your slow commands and try to find a way to handle this before sending the command to redis. If you use a keys command you might want to switch to [scan](http://redis.io/commands/scan).

The reason why this is not really possible to fix client side is, that the respond time may take long because there's either a latency problem with the connection or redis itself needs very long to compute the response. If redis takes very long no other command would be handled even if we return an error for the running command and the client would still have to wait for the response of the running command. 

This might be possible to handle with cluster by using another redis instance while the one is still computing but this has to be done by the cluster code and node_redis does not have a built-in cluster mode yet.

**Comment by sseppola** [comment]
@shezarkhani this may be too late, but if you use bluebird you can use its built in .timeout() function: http://bluebirdjs.com/docs/api/timeout.html
This does not solve the problem mentioned above, but your application code will not hang.

**Comment by cly19891215** [comment]
Hi BridgeAR,

This command timeout feature is very important when Redis server service is unstable.
Is there a plan to implement it ？

Thanks

**Comment by BridgeAR** [comment]
@cly19891215 I decided not to implement a command timeout directly but a way to detect broken connections earlier. That implementation should also be able to detect long running commands and I consider printing a warning in that case, since simply rejecting that command would be a faulty behavior.

**Comment by mrhaynesy** [comment]
Hi Guys, 

We are experiencing the same issue and have come to the same conclusion to use timeout from Bluebird. For our issue, the network between AWS regions would drop our connection and that would take around 15 minutes for Redis to notice and reconnect.

What would be nice is if we could tell the client to reconnect in our catch statement allowing re-establish of the client before continuing.

Here is the snippet we are currently using:

```
return this.redisClient.setAsync("key","value")
  .timeout(this.timeoutMs)
  .catch(Promise.TimeoutError, e => {
         var oldConnection = this.redisClient;
         this.redisClient = this.createRedisClient();
         oldConnection.end(false);
```
the issues is that we are recreating redisClient and need to keep track of all these clients we create/destroy manage pub/sub to them etc. Would be cool if we can do `redisClient.dropAndReconnect()`
